# Pytorch的核心概念

Pytorch是一个基于Python的机器学习库。它广泛应用于计算机视觉，自然语言处理等深度学习领域。是目前和TensorFlow分庭抗礼的深度学习框架，**在学术圈颇受欢迎**

它主要提供了以下两种核心功能：

1.支持GPU加速的张量计算。

2.方便优化模型的自动微分机制。
Pytorch的主要优点：

1. 简洁易懂：Pytorch的API设计的相当简洁一致。基本上就是tensor, autograd, nn三级封装。

2. 便于调试：Pytorch采用动态图，可以像普通Python代码一样进行调试。不同于TensorFlow, Pytorch的报错说明通常很容易看懂。

3. 强大高效：Pytorch提供了非常丰富的模型组件，可以快速实现想法。并且运行速度很快。目前大部分深度学习相关的Paper都是用Pytorch实现的。

Pytorch底层最核心的概念是:
1. **张量**
2. **动态计算图**
3. **自动微分**


# 张量数据结构

Pytorch的基本数据结构是张量Tensor。张量即多维数组

Pytorch的张量和numpy中的array很类似
本节内容：
1. 张量的数据类型
2. 张量的维度
3. 张量的尺寸
4. 张量和numpy数组

## 张量的数据类型

张量的数据类型和numpy.array基本一一对应，但是不支持str类型
包括:
1. torch.float64(torch.double),
2. **torch.float32(torch.float)**
3. torch.float16,
4. torch.int64(torch.long),
5. torch.int32(torch.int),
6. torch.int16,
7. torch.int8,
8. torch.uint8,
9. torch.bool

**一般神经网络建模使用的都是torch.float32类型**

**自动判断数据类型**

In [2]:
import numpy as np
import torch
i = torch.tensor(1);
print(i, i.dtype)

x = torch.tensor(2.0)
print(x, x.dtype)

b = torch.tensor(True)
print(b, b.dtype)

tensor(1) torch.int64
tensor(2.) torch.float32
tensor(True) torch.bool


**指定数据类型**

In [3]:
i = torch.tensor(1, dtype= torch.int32)
print(i, i.dtype)

x = torch.tensor(2.0, dtype=torch.double)
print(x, x.dtype)

tensor(1, dtype=torch.int32) torch.int32
tensor(2., dtype=torch.float64) torch.float64


**使用特定类构造函数**

In [7]:
i = torch.IntTensor(1)
print(i, i.dtype)

# 等价于Torch.FloatTensor
x = torch.Tensor(np.array(2.0))
print(x, x.dtype)

#x_f = torch.FloatTensor(2.0)
# 注意上面的写法会报错，data must be a sequence
x_f = torch.FloatTensor(np.array(2.0))
print(x_f, x_f.dtype)

b = torch.BoolTensor(np.array([1,0,2,0]))
print(b,b.dtype)


tensor([712248608], dtype=torch.int32) torch.int32
tensor(2.) torch.float32
tensor(2.) torch.float32
tensor([ True, False,  True, False]) torch.bool


**不同类型进行转换**
有三种方法：
1. 调用float(), int()
2. 调用type(torch.int) 
3. 调用type_as(x)

In [15]:
i = torch.tensor(1)
print(i,i.dtype)

#int64abs --> float32
# 调用float()方法进行转换
x = i.float()
print(x, x.dtype)

# 调用type()函数进行转换
y = i.type(torch.float)
print(y,y.dtype)

#使用type_as转换成与指定张量类型相同的类型
z = i.type_as(x)
print(z,z.dtype)

tensor(1) torch.int64
tensor(1.) torch.float32
tensor(1.) torch.float32
tensor(1.) torch.float32


## 张量的维度

不同类型的数据可以用不同维度(dimension)的张量来表示：
1. 标量是0维张量
2. 向量是1维张量
3. 矩阵是2维张量

...

彩色图像有rgb三个通道，可以表示为3维张量

视频还有时间维，可以表示为4维张量

**可以简单地总结为：有几层中括号，就是多少维的张量**

In [18]:
# 标量
scalar = torch.tensor(True)
print("标量")
print(scalar, scalar.dim())

# 向量 
vector = torch.tensor([1.,2.,3.,4.,5.])
print("向量")
print(vector, vector.dim())

# 矩阵
matrix = torch.tensor([[1.,2.,3.,],[4.,5.,6.]])
print("矩阵")
print(matrix, matrix.dim())

标量
tensor(True) 0
向量
tensor([1., 2., 3., 4., 5.]) 1
矩阵
tensor([[1., 2., 3.],
        [4., 5., 6.]]) 2


## 张量的尺寸

1. 可以使用` shape`属性或者 `size()`方法查看张量在每一维的长度
2. 可以使用`view`方法改变张量的尺寸
3. 如果`view`方法改变尺寸失败，可以使用`reshape`方法